apiVersion: batch/v1
kind: Job
metadata:
 name: test-local-job
 labels:
  type: ephemeral
  env: local
spec:
 template:
  spec: 
   containers: 
   - name: busybox-job
     image: busybox
     command: ['/bin/sh', '-c', 'echo Hello Kubernetes !']
   restartPolicy: Never
 backoffLimit: 2

