apiVersion: v1
kind: Pod
metadata:
 name: local-pod-secret
spec:
 containers:
 - name: pod-secret1
   image: busybox
   command: ['sh', '-c', "echo $(MY_SECRET_KEY) && sleep 600"]
   env:
   - name: MY_SECRET_KEY
     valueFrom:
      secretKeyRef:
       name: local-secret
       key: local-addr
        
